### ISSUE TITLE
Players that headhit are getting reset by trigger_teleports

### ISSUE THREAD

**Issue by ghost** [GAMMACASE/HeadBugFix#1] opened 2022-02-08 13:32 UTC
After a player reported the bug I tested myself and I was getting reset due to head hitting a part that you normally want to head hit. I disabled the plugin and it didn't reset me a single time

Video I was sent: 
https://user-images.githubusercontent.com/16860411/152997390-1f129dcf-8251-452e-9ad2-29150d57db8c.mp4

**Comment by GAMMACASE** [comment] 2022-02-08 13:54
What map is it?

**Comment by GAMMACASE** [comment] 2022-02-08 18:48
The logic of this plugin is ran only when client is ducking, which I'm unable to tell from the video example as there are no keys displayed on the screen, so if you could also answer if the ducking was used or not that would be helpful.

**Comment by ghost** [comment] 2022-02-20 03:08
> The logic of this plugin is ran only when client is ducking, which I'm unable to tell from the video example as there are no keys displayed on the screen, so if you could also answer if the ducking was used or not that would be helpful.

When testing myself I wasn't ducking, just headhitting as you are supposed to there if you want a decent time. Map is surf_treespam stage 4 (shown in video). 

I opened the map up in hammer and the border under the glass is where you hit the trigger. I opened it just to check it wasn't a map issue the trigger doesn't exist there except the floor above (maybe it has to do with the floor being like a grate? I'm not sure
![image](https://user-images.githubusercontent.com/16860411/154826860-affb5b6d-2156-4d8b-8327-4bb2c5e73092.png)


Sorry for late response it didn't email me sadly

**Comment by GAMMACASE** [comment] 2022-02-20 19:48
Can you please verify that the map you named (surf_treespam) is actually the map in the video, cuz it doesn't seem to match, and even the skybox texture is different. Or if you can, link the map directly to a download or upload it somewhere where I could download directly (cuz surf_treespam wasn't available anywhere publicly, so I went ahead and downloaded it from the gflclan servers (I assume the ones shown in the video) and yet it's still doesn't match).

**Comment by ghost** [comment] 2022-02-21 06:37
> Can you please verify that the map you named (surf_treespam) is actually the map in the video, cuz it doesn't seem to match, and even the skybox texture is different. Or if you can, link the map directly to a download or upload it somewhere where I could download directly (cuz surf_treespam wasn't available anywhere publicly, so I went ahead and downloaded it from the gflclan servers (I assume the ones shown in the video) and yet it's still doesn't match).

I am so sorry... I always get these 2 damn maps mixed. surf_treefort is the map in the example I gave. I can 100% reproduce it on video if you'd like. All I have to do is unload the plugin and it won't happen (from when I was testing)

**Comment by GAMMACASE** [comment] 2022-02-21 21:41
Seems like something else is altering this plugin and causes the said issues, I'm unable to reproduce the problem in my testing environment (https://streamable.com/1pcgb5). Can you please remove all plugins and extensions and test only with the timer and this plugin. Also if you do have custom player models etc, you might also want to test with the default models too. Also if you could provide ``sm plugins list`` and ``sm exts list``, I might try to identify the problematic plugin, but I wont guarantee that if you do run a lot of private plugins, in such case you'd better to remove plugins one by one (only leaving headbugfix) to see when the problem is fixed.

**Comment by ghost** [comment] 2022-02-23 09:01
Yeah I'm not sure what it could be, not too much issue then if it's on my end. I tested on a server with only few plugins and it seemed fine but this one has old csgo models forced on to prevent issues. So, like you said if I had to guess it's issue with newer models or another plugin I suppose. I won't worry about it too much as it wasn't really needed for my server set up. Thank you for taking the time however (and if you want a full plugin list I could still provide). Besides that though you can close since it's only a me thing

**Comment by GAMMACASE** [comment] 2022-02-23 10:55
My testing environment also uses new csgo models (no alterations to them at all), so that shouldn't be the problem.

Alright, I'll close this for now, feel free to reopen once you'd have more info on this or lmk if you find the cause, would be useful to know.

**Closed as completed** 2022-02-23 10:55 UTC
Labels: question
